### ISSUE TITLE
DEVICE REMOVED (bug in Npcap)

### ISSUE THREAD

**Issue by julianodesanti** [nmap/npcap#505] opened 2021-06-06 22:45 UTC
Hello, Im here following the instructions by Wireshark pop-up window about a error during a capture.

I do this before in the Gitlab (same problem: device removed), now Im here to continue colaborating

If Im missing something, please comment, thank for your attention

![wireshark](https://user-images.githubusercontent.com/85462414/120942496-b6288100-c6ff-11eb-8018-e5221fd3c22d.jpg)

**Comment by guyharris** [comment] 2021-06-06 22:55
Same issue as #504.

**Comment by guyharris** [comment] 2021-06-06 22:59
The full instructions also include, in the "Give all details, such as" section:

> Any indication of whether the machine went to sleep during the capture;       
> Any indication of whether any other interfaces were added to or removed from the machine while the capture was taking place.

Did the machine go to sleep during the capture, and were any other interfaces added to or removed from the machine while the capture was taking place?

**Comment by guyharris** [comment] 2021-06-07 05:59
And another question brought up by what the submitter of #504 said - is that Wi-Fi adapter built in, or is it a USB adapter?

**Comment by guyharris** [comment] 2021-06-07 06:04
See also #250.

**Comment by julianodesanti** [comment] 2021-06-07 12:42
> The full instructions also include, in the "Give all details, such as" section:
> 
> > Any indication of whether the machine went to sleep during the capture;
> > Any indication of whether any other interfaces were added to or removed from the machine while the capture was taking place.
> 
> Did the machine go to sleep during the capture, and were any other interfaces added to or removed from the machine while the capture was taking place?

No sleep mode and none of other interfaces added. But I have a clue. 

The reason I started the capture was because I was momentarily experiencing conflict in the data traffic, I mean, my connection was precarious at that time. You know, when you load the web page but you don't load the images? So that's why I decided to capture to better understand the situation. However, because of this low connection quality, the wi-fi adapter has soothed.

**Comment by dmiller-nmap** [comment] 2021-06-07 21:24
This error happens when NDIS detaches Npcap's filter driver from the adapter, as discussed at #250. For long-running captures, we recommend minding the software and restarting the capture as soon as this error is seen. This can be done directly with dumpcap.exe, but I do not know whether Wireshark supports it directly.

I am closing this as a duplicate of #250. I have opened #506 for discussion of a new feature to work around this behavior.

**Closed by dmiller-nmap** 2021-06-07 21:24 UTC
