### ISSUE TITLE
send error: PacketSendPacket failed: The I/O operation failed because network media is disconnected or wireless access point is out of range

### ISSUE THREAD

**Issue by farcas-snps** [nmap/npcap#638] opened 2022-09-29 05:19 UTC
When switching from Npcap version 1.60 to 1.70 I started to get the following error for some network interfaces:
`send error: PacketSendPacket failed: The I/O operation failed because network media is disconnected or wireless access point is out of range.  (2150891551).`

Any idea what causes this error?

I am on a Windows 10 machine, doing read/write operations on network interfaces.

**Comment by dmiller-nmap** [comment] 2022-10-03 19:22
Thanks for this report. Npcap 1.70 introduced a new behavior where Write IRPs (the system call behind all Npcap's packet injection operations) can be pended until the send is complete, which means the driver now returns a real status code for each send operation. Previously, all Write operations (packet injections, e.g. `PacketSendPacket()`) would return a success status, regardless of whether the packet was sent or not.

Closing as expected behavior. If you want the previous behavior, ignore the return value from `pcap_inject()`, `pcap_sendpacket()`, or `PacketSendPacket()`.

**Closed by dmiller-nmap** 2022-10-03 19:22 UTC

**Comment by farcas-snps** [comment] 2022-10-04 11:02
Hi @dmiller-nmap,
Thanks for your response. By ignoring the return value of `pcap_inject()`, `pcap_sendpacket()`, or `PacketSendPacket()` we consider these operations to always be completed successfully. Is this true?

**Comment by guyharris** [comment] 2022-10-05 01:13
> By ignoring the return value of pcap_inject(), pcap_sendpacket(), or PacketSendPacket() we consider these operations to always be completed successfully. Is this true?

As I understand what Daniel said:

- prior to 1.70, packet sends are not guaranteed to complete successfully, and the code trying to send them is *not* informed if a send fails to complete, so your program would have no idea whether a send failed or not;
- starting in 1.70, packet sends are *still* not guaranteed to complete successfully (such a guarantee can't be offered by software), but at least the code trying to send them is informed if a send fails to complete.

So your choices are:

1. send packets and don't check whether that they were transmitted, and assume they were;
2. send packets and check whether they were transmitted, and if they're not, do something appropriate.

With a pre-1.70 release, choice 2 has the same results as choice 1, because, if you check whether the packet was transmitted, the answer will be "yes" whether the packet was transmitted or not.

With 1.70 or later, choice 1 doesn't require you to handle the "not transmitted" case, but choice 2, while it does require to handle it, at least allows you to retransmit the packet or something such as that.

**Comment by farcas-snps** [comment] 2022-10-05 12:17
The packets are transmitted even though `pcap_sendpacket()` returns error. I can capture them with Wireshark.
What I understand is that packets cannot be transmitted right away, they are queued in a list and an error is returned. But they are eventually transmitted successfully.
