### ISSUE TITLE
Failed to create the npcap service: 0x800f0203 (arm64 compatibility)

### ISSUE THREAD

**Issue by BrightSu02** [nmap/npcap#273] opened 2020-12-27 02:37 UTC
Hello,

I tried to install Npcap on my Windows 10 (ARM64), and it returned: 
Failed to create the npcap service: 0x800f0203
As I searched for the error code I learnt that Windows 10 on ARM does not support emulation of x86 kernel-mode drivers, and the drivers must be recompiled to ARM64. (source: https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/building-arm64-drivers)

Can you add arm64 driver support if possible? thx

**Comment by guyharris** [comment] 2020-12-27 05:41
> Hello,
> 
> I tried to install Npcap on my Windows 10 (ARM64), and it returned:
> Failed to create the npcap service: 0x800f0203
> As I searched for the error code I learnt that Windows 10 on ARM does not support emulation of x86 kernel-mode drivers,

Few if any cross-platform operating systems do; they may do interpretation or binary translation of user-mode binaries, but tend not to do it in the kernel.  (The x86 version of macOS didn't support PowerPC driver binaries, and the ARM64 version of macOS doesn't support x86-64 driver binaries.)

> Can you add arm64 driver support if possible? thx

This is a duplicate of issue #57.  There's a pull request, #18, for this, but it needs to be rebased, *and* supporting a new platform, as noted in [a comment on that pull request](https://github.com/nmap/npcap/pull/18#issuecomment-632908931), requires more effort than just checking in a commit to add that support.

**Comment by guyharris** [comment] 2020-12-27 06:29
...although if the installer could, for now, be made to report "ARM isn't supported" and refuse to install, that might be a good temporary fix (pending ARM64 support).

**Comment by fyodor** [comment] 2020-12-27 22:58
Duplicate of #57

**Closed by fyodor** 2020-12-27 22:58 UTC
