### ISSUE TITLE
Wireshark Not Detecting Dell VPN Packets with npcap 1.0.0

### ISSUE THREAD

**Issue by gabbiccino** [nmap/npcap#257] opened 2020-11-06 11:24 UTC
Hi,

I'm seeing quite an odd issue at the moment and need some help. I don't have much info but can provide more, if there are specific troubleshooting methods or logging that I can be pointed towards - however this seems to be quite an unusual scenario.

The issue is that we're using a Dell SonicWall VPN interface with the Global VPN Client, and when Wireshark is installed with npcap 1.0.0 it detects no packets on the VPN interface itself. 

More bizarrely, if we install WinPCAP 4.1.3 and reinstall Wireshark before uninstalling npcap 1.0.0, Wireshark **does** then start to pick up packets on exactly the same interface.

I've tried some suggestions from another issue (https://github.com/nmap/npcap/issues/78), but received errors:

![image](https://user-images.githubusercontent.com/11510282/98359935-de90b580-2020-11eb-92f0-ddd2b1802bbf.png)

> c:\Program Files\Npcap>NPFInstall.exe -i
Unknown error! e000024b
Npcap LWF driver has failed to be installed.

Here is the output from `ipconfig`:

> C:\Users\user.test1>ipconfig /all

> Windows IP Configuration
> 
>    Host Name . . . . . . . . . . . . : TEST-PC
>    Primary Dns Suffix  . . . . . . . : test.com
>    Node Type . . . . . . . . . . . . : Hybrid
>    IP Routing Enabled. . . . . . . . : No
>    WINS Proxy Enabled. . . . . . . . : No
>    DNS Suffix Search List. . . . . . : test.com
>                                        test.home
> 
> Ethernet adapter Ethernet 2:
> 
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : SonicWALL Virtual NIC
>    Physical Address. . . . . . . . . : 40-60-23-23-F9-2A
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::78db:70e2:6c6e:d116%10(Preferred)
>    IPv4 Address. . . . . . . . . . . : 10.0.227.71(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.252.0
>    Lease Obtained. . . . . . . . . . : Thursday, November 5, 2020 1:20:53 AM
>    Lease Expires . . . . . . . . . . : Thursday, November 5, 2020 4:20:56 PM
>    Default Gateway . . . . . . . . . : 0.0.0.0
>    DHCP Server . . . . . . . . . . . : 10.0.224.10
>    DHCPv6 IAID . . . . . . . . . . . : 1052133299
>    DHCPv6 Client DUID. . . . . . . . : 00-01-00-02-24-C1-E5-2A-28-D2-14-22-DE-2C
>    DNS Servers . . . . . . . . . . . : 10.0.5.80
>                                        10.0.5.60
>                                        4.2.2.2
>    NetBIOS over Tcpip. . . . . . . . : Enabled
> 
> Ethernet adapter Ethernet:
> 
>    Media State . . . . . . . . . . . : Media disconnected
>    Connection-specific DNS Suffix  . : test.home
>    Description . . . . . . . . . . . : Intel(R) 82579LM Gigabit Network Connection
>    Physical Address. . . . . . . . . : 28-D2-44-55-DE-0C
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
> 
> Wireless LAN adapter Local Area Connection* 1:
> 
>    Media State . . . . . . . . . . . : Media disconnected
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
>    Physical Address. . . . . . . . . : E0-9D-31-3D-49-DD
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
> 
> Wireless LAN adapter Local Area Connection* 2:
> 
>    Media State . . . . . . . . . . . : Media disconnected
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
>    Physical Address. . . . . . . . . : E2-9D-31-3D-49-DC
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
> 
> Wireless LAN adapter Wi-Fi:
> 
>    Connection-specific DNS Suffix  . : test.home
>    Description . . . . . . . . . . . : Intel(R) Centrino(R) Advanced-N 6205
>    Physical Address. . . . . . . . . : EA-3D-31-32-44-D2
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::d9da:23a0:7fa0:a1a0%2(Preferred)
>    IPv4 Address. . . . . . . . . . . : 192.168.0.16(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.255.0
>    Lease Obtained. . . . . . . . . . : Monday, November 2, 2020 9:02:47 AM
>    Lease Expires . . . . . . . . . . : Wednesday, November 11, 2020 7:46:25 AM
>    Default Gateway . . . . . . . . . : 192.168.0.1
>    DHCP Server . . . . . . . . . . . : 192.168.0.1
>    DHCPv6 IAID . . . . . . . . . . . : 48274737
>    DHCPv6 Client DUID. . . . . . . . : 00-41-00-01-24-C1-D5-3A-18-E6-11-12-FA-2E
>    DNS Servers . . . . . . . . . . . : 168.2.111.133
>                                        168.2.127.13
>    NetBIOS over Tcpip. . . . . . . . : Enabled

In this case, "Ethernet 2" is the VPN interface where we see packets when using WinPCap, but not when using npcap.

Below is the output from ` NetAdapter -Name "Ethernet 2" | select * | fl` on this machine:

> MacAddress                                       : 00-60-73-54-F9-5A
> Status                                           : Up
> LinkSpeed                                        : 144 Mbps
> MediaType                                        : 802.3
> PhysicalMediaType                                : 802.3
> AdminStatus                                      : Up
> MediaConnectionState                             : Connected
> DriverInformation                                : Driver Date 2009-01-08 Version 10.1.0.40 NDIS 5.0
> DriverFileName                                   : swvnic.sys
> NdisVersion                                      : 5.0
> ifOperStatus                                     : Up
> ifAlias                                          : Ethernet 2
> InterfaceAlias                                   : Ethernet 2
> ifIndex                                          : 10
> ifDesc                                           : SonicWALL Virtual NIC
> ifName                                           : ethernet_32774
> DriverVersion                                    : 10.1.0.40
> LinkLayerAddress                                 : 00-60-73-54-F9-5A
> Caption                                          :
> Description                                      :
> ElementName                                      :
> InstanceID                                       : {36CB369C-E0C0-4DF4-8E8C-F5F63389D0F0}
> CommunicationStatus                              :
> DetailedStatus                                   :
> HealthState                                      :
> InstallDate                                      :
> Name                                             : Ethernet 2
> OperatingStatus                                  :
> OperationalStatus                                :
> PrimaryStatus                                    :
> StatusDescriptions                               :
> AvailableRequestedStates                         :
> EnabledDefault                                   : 2
> EnabledState                                     : 5
> OtherEnabledState                                :
> RequestedState                                   : 12
> TimeOfLastStateChange                            :
> TransitioningToState                             : 12
> AdditionalAvailability                           :
> Availability                                     :
> CreationClassName                                : MSFT_NetAdapter
> DeviceID                                         : {36CB369C-E0C0-4DF4-8E8C-F5F63389D0F0}
> ErrorCleared                                     :
> ErrorDescription                                 :
> IdentifyingDescriptions                          :
> LastErrorCode                                    :
> MaxQuiesceTime                                   :
> OtherIdentifyingInfo                             :
> PowerManagementCapabilities                      :
> PowerManagementSupported                         :
> PowerOnHours                                     :
> StatusInfo                                       :
> SystemCreationClassName                          : CIM_NetworkPort
> SystemName                                       : TEST-PC.test.com
> TotalPowerOnHours                                :
> MaxSpeed                                         :
> OtherPortType                                    :
> PortType                                         :
> RequestedSpeed                                   :
> Speed                                            : 144000000
> UsageRestriction                                 :
> ActiveMaximumTransmissionUnit                    : 1418
> AutoSense                                        :
> FullDuplex                                       :
> LinkTechnology                                   :
> NetworkAddresses                                 : {00607354F95A}
> OtherLinkTechnology                              :
> OtherNetworkPortType                             :
> PermanentAddress                                 : 00607354F95A
> PortNumber                                       : 0
> SupportedMaximumTransmissionUnit                 :
> AdminLocked                                      : False
> ComponentID                                      : *sw_virtualnic
> ConnectorPresent                                 : False
> DeviceName                                       : \Device\{36CB369C-E0C0-4DF4-8E8C-F5F63389D0F0}
> DeviceWakeUpEnable                               : False
> DriverDate                                       : 2009-01-08
> DriverDateData                                   : 128758464000000000
> DriverDescription                                : SonicWALL Virtual NIC
> DriverMajorNdisVersion                           : 5
> DriverMinorNdisVersion                           : 0
> DriverName                                       : \SystemRoot\System32\drivers\swvnic.sys
> DriverProvider                                   : SonicWALL
> DriverVersionString                              : 10.1.0.40
> EndPointInterface                                : False
> HardwareInterface                                : False
> Hidden                                           : False
> HigherLayerInterfaceIndices                      : {59}
> IMFilter                                         : False
> InterfaceAdminStatus                             : 1
> InterfaceDescription                             : SonicWALL Virtual NIC
> InterfaceGuid                                    : {36CB369C-E0C0-4DF4-8E8C-F5F63389D0F0}
> InterfaceIndex                                   : 10
> InterfaceName                                    : ethernet_32774
> InterfaceOperationalStatus                       : 1
> InterfaceType                                    : 6
> iSCSIInterface                                   : False
> LowerLayerInterfaceIndices                       :
> MajorDriverVersion                               : 0
> MediaConnectState                                : 1
> MediaDuplexState                                 : 0
> MinorDriverVersion                               : 1
> MtuSize                                          : 1418
> NdisMedium                                       : 0
> NdisPhysicalMedium                               : 14
> NetLuid                                          : 1689399716741120
> NetLuidIndex                                     : 32774
> NotUserRemovable                                 : False
> OperationalStatusDownDefaultPortNotAuthenticated : False
> OperationalStatusDownInterfacePaused             : False
> OperationalStatusDownLowPowerState               : False
> OperationalStatusDownMediaDisconnected           : False
> PnPDeviceID                                      : ROOT\SWVNIC\0000
> PromiscuousMode                                  : True
> ReceiveLinkSpeed                                 : 144000000
> State                                            : 2
> TransmitLinkSpeed                                : 144000000
> Virtual                                          : True
> VlanID                                           :
> WdmInterface                                     : False
> PSComputerName                                   :
> CimClass                                         : ROOT/StandardCimv2:MSFT_NetAdapter
> CimInstanceProperties                            : {Caption, Description, ElementName, InstanceID...}
> CimSystemProperties                              : Microsoft.Management.Infrastructure.CimSystemProperties
> 

--

I should add that in both cases, packets are received on other interfaces. For example, the wifi connection above is the interface in use for Internet connection and that shows packets for both WinPCap and npcap, so this appears to be specifically an issue when using npcap with this particular VPN interface.

Would anyone be able to help with this please?

Many thanks in advance.

**Comment by gabbiccino** [comment] 2020-11-16 15:12
[DiagReport-20201116-090855.txt](https://github.com/nmap/npcap/files/5547164/DiagReport-20201116-090855.txt)

Attaching the diagreport output too. I'm still experiencing this issue with v 1.0.0 of npcap.

I also today tried running the following, which did show packets in the trace:

`netsh trace start capture=yes CaptureInterface="Ethernet 2" tracefile=%userprofile%\test3.etl`

Running a Wireshark trace with npcap at the same time showed no packets at all.

**Comment by gabbiccino** [comment] 2020-11-16 18:12
> What traffic is shown when capturing on the other interface ("Wireless LAN adapter Wi-Fi") while using the VPN? I would expect it would show the encrypted VPN traffic.

Yes that is correct, I see only ESP packets.

**Comment by guyharris** [comment] 2020-11-16 18:33
> I suspect this might be because of the Npcap driver's [`FilterClass`](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/configuring-an-inf-file-for-a-modifying-filter-driver), which is "compression" and comes above "vpn" in the stack. This is complete conjecture at the moment, while I research how to verify, but it is _possible_ that the VPN driver is injecting the encrypted traffic below the Npcap driver so that it does not see any of it. WinPcap, implemented as a protocol driver, sits at the top of the stack and uses (costly) internal NDIS loopback mechanisms to see outgoing traffic regardless of where it was injected in the stack.

So what *is* the appropriate place for the Npcap driver?  At least as I understand the Microsoft documentation, "diagnostic" or "custom" would put it closer to the miniport driver, but are there any issues with that?

**Comment by gabbiccino** [comment] 2020-11-16 18:34
> Thanks for this report. So as I understand the issue, Npcap has no problem _showing_ this interface as available for capture, but it does not actually capture any traffic on it?

That's correct - though I should add that the capture on the VPN interface does show a few packets while the VPN client is connecting. Afterwards, it shows nothing for HTTP/RTP traffic that we know is there, because WinPCap shows it during a capture.

**Comment by dmiller-nmap** [comment] 2020-11-16 22:44
@gabbiccino What kind of packets are shown while the VPN client is connecting? There is a known issue (related to nmap/nmap#989) where certain OS and NIC configuration options can bypass the part of the stack where Npcap sits. Specifically, [TCP Chimney Offload](https://support.microsoft.com/en-us/help/951037/information-about-the-tcp-chimney-offload-receive-side-scaling-and-net) may result in only the first few TCP setup packets being received, with subsequent data packets going directly to a lower driver (usually the NIC, but I can see how this could be used to implement a VPN). There is a similar IPSec Offload which may be interfering, too. What do you get for the following commands (powershell)?

1. `Get-NetAdapterIPsecOffload`
2. `Get-NetAdapterAdvancedProperty "Ethernet 2" -AllProperties |select DisplayName,DisplayValue,RegistryKeyword,RegistryValue |fl`
3. `Get-NetAdapterEncapsulatedPacketTaskOffload`
4. `netsh int tcp show global`

**Comment by gabbiccino** [comment] 2020-11-17 14:41
Hi @dmiller-nmap,

Here's the output from the commands (1st and 3rd command gave no response):

> PS C:\Users\admin.HN-328> Get-NetAdapterIPsecOffload
> PS C:\Users\admin.HN-328> Get-NetAdapterAdvancedProperty "Ethernet 2" -AllProperties |select DisplayName,DisplayValue,RegistryKeyword,RegistryValue |fl
> 
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : DriverDesc
> RegistryValue   : {SonicWALL Virtual NIC}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : ProviderName
> RegistryValue   : {SonicWALL}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : DriverDate
> RegistryValue   : {1-8-2009}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : DriverVersion
> RegistryValue   : {10.1.0.40}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : InfPath
> RegistryValue   : {oem14.inf}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : InfSection
> RegistryValue   : {SWVNIC.ndi}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : MatchingDeviceId
> RegistryValue   : {*sw_virtualnic}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : BusNumber
> RegistryValue   : {0}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : *IfType
> RegistryValue   : {6}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : *MediaType
> RegistryValue   : {0}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : *PhysicalMediaType
> RegistryValue   : {14}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : Characteristics
> RegistryValue   : {129}
> 
> DisplayName     : Network Address
> DisplayValue    : 0060735B7991
> RegistryKeyword : NetworkAddress
> RegistryValue   : {0060735B7991}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : IfTypePreStart
> RegistryValue   : {6}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : NetworkInterfaceInstallTimestamp
> RegistryValue   : {132487425097788726}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : DeviceInstanceID
> RegistryValue   : {ROOT\SWVNIC\0000}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : ComponentId
> RegistryValue   : {*sw_virtualnic}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : NetCfgInstanceId
> RegistryValue   : {{7CAA0DF8-3303-4058-AB29-B1E0FE7AAEE0}}
> 
> DisplayName     :
> DisplayValue    :
> RegistryKeyword : NetLuidIndex
> RegistryValue   : {32770}
> 
> 
> 
> PS C:\Users\admin.HN-328> Get-NetAdapterEncapsulatedPacketTaskOffload
> PS C:\Users\admin.HN-328> netsh int tcp show global
> Querying active state...
> 
> TCP Global Parameters
> ----------------------------------------------
> Receive-Side Scaling State          : enabled
> Receive Window Auto-Tuning Level    : normal
> Add-On Congestion Control Provider  : default
> ECN Capability                      : disabled
> RFC 1323 Timestamps                 : disabled
> Initial RTO                         : 1000
> Receive Segment Coalescing State    : enabled
> Non Sack Rtt Resiliency             : disabled
> Max SYN Retransmissions             : 4
> Fast Open                           : enabled
> Fast Open Fallback                  : enabled
> HyStart                             : enabled
> Pacing Profile                      : off

**Comment by gabbiccino** [comment] 2020-11-17 14:58
> @gabbiccino What kind of packets are shown while the VPN client is connecting?

While the VPN is connecting, we see the following:

![image](https://user-images.githubusercontent.com/11510282/99405061-3b735200-28e4-11eb-90eb-65c6c84268f9.png)

![image](https://user-images.githubusercontent.com/11510282/99404740-e46d7d00-28e3-11eb-9f28-c7e6f4418b86.png)

After the connection is established, Wireshark very occasionally shows a few MDNS packets, e.g.:

![image](https://user-images.githubusercontent.com/11510282/99404816-f94a1080-28e3-11eb-89ff-b60cd3726356.png)

If I then use a web browser to navigate, I see nothing in Wireshark but the "Properties" window for the adapter in the Global VPN Client shows packets. The status window for the VPN interface in Windows Network Connections shows a much smaller number:

![image](https://user-images.githubusercontent.com/11510282/99405886-2814b680-28e5-11eb-91a6-63318bf2fe64.png)

**Comment by dmiller-nmap** [comment] 2020-11-23 18:03
I have an idea for a workaround, but I need to test to see if it will work. The basic idea is this: WinPcap, as a NDIS protocol driver, uses the `NDIS_PACKET_TYPE_ALL_LOCAL` packet filter to loop outgoing packets back up the stack, which is how it would be able to see these VPN packets. Npcap doesn't allow this filter to be set, since it's an inefficient path and Npcap should be able to see all packets flowing through the stack already. However, we might need to preserve the ability to set this for unusual cases like yours.

To test this, can you please download and install [Npcap 0.9989](https://nmap.org/npcap/dist/npcap-0.9989.exe) (the last version to use the `NDIS_PACKET_TYPE_ALL_LOCAL` filter) and see if Wireshark can see the traffic you expect?

**Comment by gabbiccino** [comment] 2020-11-24 13:20
@dmiller-nmap thanks for the response. I tried Npcap 0.9989 but the displayed packets appear to be the same as with version 1.0. Are there different installation options that I should set during install? I tried enabling the loopback option presented during install but saw the same results. 

Is there any information that I could gather from when WinPCap is installed that would help?

**Comment by fyodor** [comment] 2021-04-08 20:13
It's too bad the NDIS_PACKET_TYPE_ALL_LOCAL filter didn't work :/.  We do have one more idea for capturing packets on this sort of driver that could possibly help, but it's a fairly large restructuring and so may be a longer term goal.  Here's the idea as @dmiller-nmap described it to me:

> Windows offers 2 different ways for drivers to inspect network traffic: NDIS LWF and WFP. Npcap uses NDIS LWF to see traffic on the stack between protocol drivers and miniport drivers. Some unusual network situations like VPNs may use a different data path that doesn't pass through our driver. WFP exists in a different part of the stack entirely, and could allow us to inspect traffic at different places, including prior to IPSEC VPN encapsulation. Because the semantics of traffic are different for WFP, we'd have to define and implement an extension to our existing API to let programs use it. The major difference is that there wouldn't be a concept of "capture traffic on this adapter" but rather "capture traffic at this point in the stack" which is pre-routing. That could be analogous to the "any" pseudo-device from libpcap on Linux.

**Comment by guyharris** [comment] 2021-04-08 21:44
> That could be analogous to the "any" pseudo-device from libpcap on Linux.

Note that the closest analogue to the "any" device on Linux would be a way to plug into the Windows networking stack with, or *without*, binding to a particular NDIS device; that's literally how the "any" device works on Linux - a PF_PACKET socket can be bound to a particular device, so that it sees only packets sent on or received from that device, or can be left unbound, in which case it sees packets sent on or received from *any* device.  The point in the networking stack isn't changed between the "any" device and regular network interfaces.

If, with WFP, there's a separate place in the networking stack to tap, then, if packets from all adapters and to all adapters can be seen at that point, then:

- if you can determine from which adapter the packet was received or to which it was sent, so that you can process only packets to or from a particular packet, then you could implement capture on the "any" device *or* capture on a particular device (or capture from a set of devices);
- if you can't determine that, then the capture would, in effect, only be able to implement traffic capture on an "any" device.

In the first case, "capture traffic on this adapter" would be orthogonal to "capture traffic at this point on the stack", with the WPF point being the only point supporting an "any" device (unless there's a way to do that using LWF).

-

**Comment by fyodor** [comment] 2024-09-27 20:36
We are closing this as a duplicate of #516 (even though that came later) since that general proposal should resolve this specific case.

**Closed by fyodor** 2024-09-27 20:36 UTC
