### ISSUE TITLE
Cannot start packet capture 1.72 on Killer E3100

### ISSUE THREAD

**Issue by desultory** [nmap/npcap#653] opened 2022-12-17 22:06 UTC
**Describe the bug**
Cannot start packet capture with wireshark or tshark on this interface

**To Reproduce**
try to start capture

**Expected behavior**
device enters promiscuous mode and capture begins

Error:
```
The capture session could not be initiated on capture device
(failed to sethardware filter to promiscuous mode: A device attached to the system is notfunctioning. (31)).
Please turn off promiscuous mode for this device
```
Build:
`22H2 22621.963`

Hardware:
`ASROCK 670e Taichi`
`Killer E3100 2.5 GBE` : `PCI\VEN_10EC&DEV_3000&SUBSYS_30001849&REV_06` 
Driver: `1125.5.112.2022`
Device status: `This device is working properly.`

`diag report (edited to remove irrelevant interfaces and mac addresses)`
```
*************************************************
DiagReport for Npcap ( https://npcap.com )
*************************************************
Script Architecture:		64-bit
Script Path:			C:\Program Files\Npcap\DiagReport.ps1
Current Time:			12/17/2022 16:03:59
Npcap install path:		C:\Program Files\Npcap
Npcap Version:			1.72
PowerShell Version:		5.1.22621.963


*************************************************
OS Info:
*************************************************


Caption                 : Microsoft Windows 11 Pro
BuildNumber             : 22621
Locale                  : 0409
MUILanguages            : {en-US}
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SystemDirectory         : C:\WINDOWS\system32
Version                 : 10.0.22621





*************************************************
CPU Info:
*************************************************


Name                      : AMD Ryzen 9 7950X 16-Core Processor            
Manufacturer              : AuthenticAMD
DeviceID                  : CPU0
NumberOfCores             : 16
NumberOfEnabledCore       : 16
NumberOfLogicalProcessors : 32
Addresswidth              : 64





*************************************************
Memory Info:
*************************************************
Size:				31865 MB (33412775936 Bytes)


*************************************************
Network Adapter(s) Info:
*************************************************



Caption             : [00000002] Killer E3100G 2.5 Gigabit Ethernet Controller
GUID                : {498CB49C-65DA-4130-AEBB-955254786B99}
Index               : 2
InterfaceIndex      : 8
Manufacturer        : Killer

Speed               : 1000000000
NetConnectionID     : Ethernet
NetConnectionStatus : 2
PNPDeviceID         : PCI\VEN_10EC&DEV_3000&SUBSYS_30001849&REV_06\0CF6E859A1A8000000
ServiceName         : e3k25cx21x64
AdapterType         : Ethernet 802.3





*************************************************
NDIS Light-Weight Filter (LWF) Info:
*************************************************
HKLM:\SYSTEM\CurrentControlSet\Control\Network\{4d36e974-e325-11ce-bfc1-08002be10318}\*:


InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_bridge
Description      : @%SystemRoot%\system32\bridgeres.dll,-2
InfPath          : netbrdg.inf
InfSection       : Install
LocDescription   : @%SystemRoot%\system32\bridgeres.dll,-2

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_wfplwf_lower
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6006
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_Lower_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6006

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 40
ComponentId      : ms_netbios
Description      : @%windir%\system32\drivers\netbios.sys,-501
InfPath          : netnb.inf
InfSection       : NetBIOS.ndi
LocDescription   : @%windir%\system32\drivers\netbios.sys,-501

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262200
ComponentId      : ms_ndiscap
Description      : @%windir%\System32\drivers\ndiscap.sys,-5000
InfPath          : ndiscap.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\ndiscap.sys,-5000

InstallTimeStamp : {230, 7, 12, 0...}
Characteristics  : 16512
ComponentId      : vmware_bridge
Description      : @oem21.inf,%vmware_desc%;VMware Bridge Protocol
InfPath          : oem21.inf
InfSection       : VMnetBridge.Install
LocDescription   : @oem21.inf,%vmware_desc%;VMware Bridge Protocol

InstallTimeStamp : {221, 7, 12, 0...}
ComponentId      : ms_server
Description      : @%systemroot%\system32\srvsvc.dll,-109
InfPath          : Netserv.inf
InfSection       : Install.ndi
LocDescription   : @%systemroot%\system32\srvsvc.dll,-109

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : vms_vsf
Description      : @%windir%\System32\drivers\vmswitch.sys,-60005
InfPath          : wvms_vsft.inf
InfSection       : VMSVSF.ndi
LocDescription   : @%windir%\System32\drivers\vmswitch.sys,-60005

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_vwifi
Description      : @%windir%\System32\drivers\vwififlt.sys,-105
InfPath          : netvwififlt.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\vwififlt.sys,-105

InstallTimeStamp : {230, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : oracle_VBoxNetLwf
Description      : @oem14.inf,%vboxnetlwf_desc%;VirtualBox NDIS6 Bridged Networking Driver
InfPath          : oem14.inf
InfSection       : VBoxNetLwf.ndi
LocDescription   : @oem14.inf,%vboxnetlwf_desc%;VirtualBox NDIS6 Bridged Networking Driver

InstallTimeStamp : {230, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : INSECURE_NPCAP
Description      : @oem27.inf,%npf_desc_standard%;Npcap Packet Driver (NPCAP)
InfPath          : oem27.inf
InfSection       : FilterStandard
LocDescription   : @oem27.inf,%npf_desc_standard%;Npcap Packet Driver (NPCAP)

InstallTimeStamp : {230, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : INSECURE_NPCAP_WIFI
Description      : @oem27.inf,%npf_desc_wifi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
InfPath          : oem27.inf
InfSection       : FilterWiFi
LocDescription   : @oem27.inf,%npf_desc_wifi%;Npcap Packet Driver (NPCAP) (Wi-Fi)

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_pacer
Description      : @%windir%\System32\drivers\pacer.sys,-101
InfPath          : netpacer.inf
InfSection       : Install
LocDescription   : @%windir%\System32\drivers\pacer.sys,-101

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_wfplwf_upper
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6005
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_Upper_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6005

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_nativewifip
Description      : @%windir%\System32\drivers\nwifi.sys,-101
InfPath          : netnwifi.inf
InfSection       : MS_NWIFI.Install
LocDescription   : @%windir%\System32\drivers\nwifi.sys,-101

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_wfplwf_vswitch
Description      : @%windir%\System32\drivers\wfplwfs.sys,-6004
InfPath          : wfplwfs.inf
InfSection       : WfpLwf_vSwitch_Install
LocDescription   : @%windir%\System32\drivers\wfplwfs.sys,-6004

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262144
ComponentId      : ms_l2bridge
Description      : @%SystemRoot%\System32\drivers\l2bridge.sys,-5000
InfPath          : l2bridge.inf
InfSection       : Install
LocDescription   : @%SystemRoot%\System32\drivers\l2bridge.sys,-5000

InstallTimeStamp : {221, 7, 12, 0...}
Characteristics  : 262184
ComponentId      : ms_winvfp
Description      : Microsoft Azure VFP Switch Filter Extension
InfPath          : vfpfilter.inf
InfSection       : Install
LocDescription   : Microsoft Azure VFP Switch Filter Extension



     
Ethernet                       Npcap Packet Driver (NPCAP)                        INSECURE_NPCAP       True         


*************************************************
File Info:
*************************************************

LastWriteTime : 11/22/2022 1:25:50 PM
Length        : 815
Name          : CheckStatus.bat


LastWriteTime : 12/17/2022 4:03:59 PM
Length        : 0
Name          : DiagReport-20221217-160359.txt


LastWriteTime : 11/22/2022 1:25:50 PM
Length        : 1073
Name          : DiagReport.bat


LastWriteTime : 11/22/2022 1:25:50 PM
Length        : 18078
Name          : DiagReport.ps1


LastWriteTime : 11/22/2022 1:25:50 PM
Length        : 2513
Name          : FixInstall.bat


LastWriteTime : 12/17/2022 3:57:34 PM
Length        : 57878
Name          : install.log


LastWriteTime : 11/22/2022 1:25:50 PM
Length        : 11784
Name          : LICENSE


LastWriteTime : 12/13/2022 10:17:22 AM
Length        : 12682
Name          : npcap.cat


LastWriteTime : 12/13/2022 10:17:22 AM
Length        : 8845
Name          : npcap.inf


LastWriteTime : 12/13/2022 10:17:22 AM
Length        : 77304
Name          : npcap.sys


LastWriteTime : 12/13/2022 10:17:22 AM
Length        : 2435
Name          : npcap_wfp.inf


LastWriteTime : 12/7/2022 3:33:18 PM
Length        : 308688
Name          : NPFInstall.exe


LastWriteTime : 12/17/2022 3:57:21 PM
Length        : 71331
Name          : NPFInstall.log


LastWriteTime : 12/13/2022 11:19:08 AM
Length        : 1083400
Name          : Uninstall.exe


Path          : C:\Program Files\Npcap\npcap.cat
Status        : Valid
StatusMessage : Signature verified.
Thumbprint    : 451B7F8A4C0E669189E9382A09E423C2B875AD42


Path          : C:\Program Files\Npcap\npcap.inf
Status        : Valid
StatusMessage : Signature verified.
Thumbprint    : 451B7F8A4C0E669189E9382A09E423C2B875AD42


Path          : C:\Program Files\Npcap\npcap.sys
Status        : Valid
StatusMessage : Signature verified.
Thumbprint    : 451B7F8A4C0E669189E9382A09E423C2B875AD42


Path          : C:\Program Files\Npcap\NPFInstall.exe
Status        : Valid
StatusMessage : Signature verified.
Thumbprint    : 3C0D087ECDCC76D1084ABE00F1FEE5040400AE37


Path          : C:\Program Files\Npcap\Uninstall.exe
Status        : Valid
StatusMessage : Signature verified.
Thumbprint    : 3C0D087ECDCC76D1084ABE00F1FEE5040400AE37


LastWriteTime : 12/7/2022 3:33:20 PM
Length        : 157136
Name          : NpcapHelper.exe


LastWriteTime : 12/7/2022 3:33:18 PM
Length        : 220624
Name          : Packet.dll


LastWriteTime : 12/7/2022 3:33:20 PM
Length        : 267216
Name          : WlanHelper.exe


LastWriteTime : 12/7/2022 3:33:18 PM
Length        : 489936
Name          : wpcap.dll


LastWriteTime : 12/7/2022 3:33:20 PM
Length        : 157136
Name          : NpcapHelper.exe


LastWriteTime : 12/7/2022 3:33:18 PM
Length        : 220624
Name          : Packet.dll


LastWriteTime : 12/7/2022 3:33:20 PM
Length        : 267216
Name          : WlanHelper.exe


LastWriteTime : 12/7/2022 3:33:18 PM
Length        : 489936
Name          : wpcap.dll


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 130512
Name          : NpcapHelper.exe


LastWriteTime : 12/7/2022 3:33:12 PM
Length        : 175056
Name          : Packet.dll


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 217040
Name          : WlanHelper.exe


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 419280
Name          : wpcap.dll


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 130512
Name          : NpcapHelper.exe


LastWriteTime : 12/7/2022 3:33:12 PM
Length        : 175056
Name          : Packet.dll


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 217040
Name          : WlanHelper.exe


LastWriteTime : 12/7/2022 3:33:14 PM
Length        : 419280
Name          : wpcap.dll



*************************************************
WinPcap Info:
*************************************************
HKLM:\SOFTWARE\WOW6432Node\WinPcap:
Not present.


*************************************************
Registry Info:
*************************************************
HKLM:\SOFTWARE\WOW6432Node\Npcap:


AdminOnly         : 0
WinPcapCompatible : 1
(default)         : C:\Program Files\Npcap



HKLM:\SYSTEM\CurrentControlSet\Services\npcap:


Type               : 1
Start              : 1
ErrorControl       : 1
Tag                : 18
ImagePath          : \SystemRoot\system32\DRIVERS\npcap.sys
DisplayName        : @oem27.inf,%NPF_Desc_Standard%;Npcap Packet Driver (NPCAP)
Group              : NDIS
Description        : @oem27.inf,%NPF_Desc_Standard%;Npcap Packet Driver (NPCAP)
NdisMajorVersion   : 6
NdisMinorVersion   : 50
DriverMajorVersion : 1
DriverMinorVersion : 72



HKLM:\SYSTEM\CurrentControlSet\Services\npcap\Parameters:


LoopbackSupport              : 1
DltNull                      : 1
Edition                      : Npcap
AdminOnly                    : 0
Dot11Support                 : 1
NdisImPlatformBindingOptions : 2
DefaultFilterSettings        : 1
VlanSupport                  : 0
WinPcapCompatible            : 1



HKLM:\SYSTEM\CurrentControlSet\Services\npcap_wifi:


Type               : 1
Start              : 4
ErrorControl       : 1
Tag                : 19
ImagePath          : \SystemRoot\system32\DRIVERS\npcap.sys
DisplayName        : @oem27.inf,%NPF_Desc_WiFi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
Group              : NDIS
Description        : @oem27.inf,%NPF_Desc_WiFi%;Npcap Packet Driver (NPCAP) (Wi-Fi)
NdisMajorVersion   : 6
NdisMinorVersion   : 50
DriverMajorVersion : 1
DriverMinorVersion : 72



HKLM:\SYSTEM\CurrentControlSet\Services\npf:
Not present.
HKLM:\SYSTEM\CurrentControlSet\Services\npf\Parameters:
Not present.
HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi:
Not present.


*************************************************
Service Info:
*************************************************

Status      : Running
Name        : npcap
DisplayName : Npcap Packet Driver (NPCAP)

Get-Service : Cannot find any service with service name 'npf'.
At C:\Program Files\Npcap\DiagReport.ps1:214 char:1
+ Get-Service npf
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npf:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand
 


*************************************************
Install Info:
*************************************************
Please refer to: C:\Program Files\Npcap\install.log
```

**Comment by guyharris** [comment] 2022-12-20 05:57
This is almost certainly a duplicate of #628.

**Comment by desultory** [comment] 2022-12-20 16:02
> This is almost certainly a duplicate of #628.

Thanks, downgrading to this seems to have fixed it for me: https://npcap.com/dist/npcap-1.60.exe

**Comment by fyodor** [comment] 2023-01-18 19:28
Thanks @desultory and @guyharris .  I agree this is a duplicate of #628, which we're working on now.  Duplicate of #628.

**Closed by fyodor** 2023-01-18 19:28 UTC
