### ISSUE TITLE
Failed to create the npcap service error 0x8007000d

### ISSUE THREAD

**Issue by SABOSO** [nmap/npcap#264] opened 2020-11-23 10:31 UTC
[setupapi.dev.txt](https://github.com/nmap/npcap/files/5582264/setupapi.dev.txt)
%SYSTEMROOT%\INF\     setupapi.dev   attached. Deleted old file for clean history. 1.00, 0.9997, 0.996
C:\WINDOWS\System32\DriverStore\FileRepository\                    Deleted npcap folder as well.

[Device Install Log]
     OS Version = 10.0.17763
     Service Pack = 0.0
     Suite = 0x0100
     ProductType = 1
     Architecture = amd64

[BeginLog]

[Boot Session: 2020/11/23 21:06:43.500]

Windows 10
Tried with different versions on npcap as well - 

  dvi: Add Service: Created service 'npcap'.
     inf: {Install from INF Section - FilterStandard.svc} 21:18:45.207
     inf:      Flags         - 0x00100004
     inf: {Install from INF Section - exit(0x00000000)} 21:18:45.207
     inf: {Install from INF Section - FilterStandard} 21:18:45.207
     inf:      Flags         - 0x00000040
     inf: {Install from INF Section - exit(0x00000000)} 21:18:45.207
     inf: {Install from INF Section - FilterStandard.Remove} 21:18:45.300
     inf:      Flags         - 0x000007af
     inf: {Install from INF Section - exit(0x00000000)} 21:18:45.300
     inf: Flags: 0x00000000
     inf: DelService=npcap,0x200  (oem6.inf line 184)
     dvi: Deleted service 'npcap'.
     inf: {Install from INF Section - FilterStandard.Remove} 21:18:45.347
     inf:      Flags         - 0x00000040
     inf: {Install from INF Section - exit(0x00000000)} 21:18:45.347
<<<  Section end 2020/11/23 21:18:45.363
<<<  [Exit status: FAILURE(0x8007007e)]

**Comment by guyharris** [comment] 2023-08-14 06:37
Same issue as #89?

**Comment by fyodor** [comment] 2023-11-27 19:01
Duplicate of #135

**Closed by fyodor** 2023-11-27 19:01 UTC
