### ISSUE TITLE
Infinite loop of packets received with length 0

### ISSUE THREAD

**Issue by alainbrassardMeca** [nmap/npcap#178] opened 2020-05-29 12:00 UTC
We're deveopping an application that uses libpcal (on Linux) and Npcap (on Windows) to capture raw Ethernet packets (we're implementing an EtherCAT stack).
Our code has been working fine for months... stop working properly after the latest Windows update (the may 2020 Windows 10 update just got installed on my PC).

Once pcap_loop is called, the attached callack is called in an infinite loop with empty packets
(the whole structure pcap_pkthdr contains only 0, and same for the packet data pointer (3rd argument).

I try reinstalling npcap.
I try changing my application to use Npcap instead of Winpcap.
I try simplifying my code calling only pcap_open_live then pcap_loop.
Still same issue.

At first sight, this looks like there may be a new incompatibility between Npcap and the latest Windows 10.

**Comment by alainbrassardMeca** [comment] 2020-05-29 12:47
Here is a small application that reproduces the issue.
(just call pcap_test_init with a local IP address then pcap_test_loop)

It can't be simpler:
- pcap_findalldevs to find appropriate device
- pcap_open_live to open the interface
- pcap_loop to start receiving packets

On my PC, since May 2020 Windows 10 update, the result of this application is:
Opened pcap device 192.168.0.119 (\Device\NPF_{D6726501-68B3-4C66-9CA5-40B4CE123EA4})
Packet 1 received, size 0
Packet 2 received, size 0
Packet 3 received, size 0
Packet 4 received, size 0
Packet 5 received, size 0
Packet 6 received, size 0
Packet 7 received, size 0
Packet 8 received, size 0
...
(and so-on infinitely as fast as fprintf can print the trace)

Here is the simple code:
------------------------------------------

#include <pcap.h>
#include <stdint.h>

pcap_t* g_hPcapDev = NULL;

static uint32_t pcap_test_inet_addr(const char* in_pIp)
{
    struct sockaddr_in sa;

    // store this IP address in sa:
    sa.sin_addr.s_addr = 0;
    inet_pton(AF_INET, in_pIp, &(sa.sin_addr));

    return sa.sin_addr.s_addr;
}

void pcap_test_init(const char* in_pIp)
{
    pcap_if_t* pDevices = NULL;
    char       errBuf[PCAP_ERRBUF_SIZE];
    uint32_t   localIp = pcap_test_inet_addr(in_pIp);

    // List all devices
    if (pcap_findalldevs(&pDevices, errBuf) == -1)
    {
        fprintf(stderr, "Failed to list devices with pcap. Error: %s\n", errBuf);
        return;
    }

    // Open the devices that matches the ip or subnet provided
    pcap_if_t* pDevice = pDevices;
    while (pDevice)
    {
        struct pcap_addr* pAddr = pDevice->addresses;
        while (pAddr)
        {
            uint32_t address = ((struct sockaddr_in*)(pAddr->addr))->sin_addr.s_addr;
            uint32_t netMask = ((struct sockaddr_in*)(pAddr->netmask))->sin_addr.s_addr;
            if (address && netMask && (address & netMask) == (localIp & netMask))
            {
                // Found the interface we were looking for. Open it with pcap
                g_hPcapDev = pcap_open_live(pDevice->name, 65536, 1, 1000, errBuf);
                if (!g_hPcapDev)
                {
                    fprintf(stderr, "Failed to open %s (%s). Error: %s\n", in_pIp, pDevice->name, errBuf);
                }
                fprintf(stdout, "Opened pcap device %s (%s)\n", in_pIp, pDevice->name);
                break;
            }
            pAddr = pAddr->next;
        }
        pDevice = pDevice->next;
    }

    if (pDevices)
    {
        pcap_freealldevs(pDevices);
    }
}

static void pcap_test_handler(
    uint8_t* in_pArg, 
    const struct pcap_pkthdr* in_pPcapHdr,
    const uint8_t* in_pData)
{
    (void)in_pArg;
    (void)in_pData;

    static uint32_t count = 0;
    fprintf(stdout, "Packet %u received, size %u\n", ++count, in_pPcapHdr->len);
}

void pcap_test_loop()
{
    if (g_hPcapDev)
    {
        pcap_loop(g_hPcapDev, 0, pcap_test_handler, NULL);
    }
}

**Comment by alainbrassardMeca** [comment] 2020-05-29 12:50
Sorry, sample code is badly formatted in previous post.
Here it is again:

    #include <pcap.h>
    #include <stdint.h>

    pcap_t* g_hPcapDev = NULL;

    static uint32_t pcap_test_inet_addr(const char* in_pIp)
    {
        struct sockaddr_in sa;

        // store this IP address in sa:
        sa.sin_addr.s_addr = 0;
        inet_pton(AF_INET, in_pIp, &(sa.sin_addr));

        return sa.sin_addr.s_addr;
    }

    void pcap_test_init(const char* in_pIp)
    {
        pcap_if_t* pDevices = NULL;
        char       errBuf[PCAP_ERRBUF_SIZE];
        uint32_t   localIp = pcap_test_inet_addr(in_pIp);

        // List all devices
        if (pcap_findalldevs(&pDevices, errBuf) == -1)
        {
            fprintf(stderr, "Failed to list devices with pcap. Error: %s\n", errBuf);
            return;
        }

        // Open the devices that matches the ip or subnet provided
        pcap_if_t* pDevice = pDevices;
        while (pDevice)
        {
            struct pcap_addr* pAddr = pDevice->addresses;
            while (pAddr)
            {
                uint32_t address = ((struct sockaddr_in*)(pAddr->addr))->sin_addr.s_addr;
                uint32_t netMask = ((struct sockaddr_in*)(pAddr->netmask))->sin_addr.s_addr;
                if (address && netMask && (address & netMask) == (localIp & netMask))
                {
                    // Found the interface we were looking for. Open it with pcap
                    g_hPcapDev = pcap_open_live(pDevice->name, 65536, 1, 1000, errBuf);
                    if (!g_hPcapDev)
                    {
                        fprintf(stderr, "Failed to open %s (%s). Error: %s\n", in_pIp, pDevice->name, errBuf);
                    }
                    fprintf(stdout, "Opened pcap device %s (%s)\n", in_pIp, pDevice->name);
                    break;
                }
                pAddr = pAddr->next;
            }
            pDevice = pDevice->next;
        }

        if (pDevices)
        {
            pcap_freealldevs(pDevices);
        }
    }

    static void pcap_test_handler(
        uint8_t* in_pArg, 
        const struct pcap_pkthdr* in_pPcapHdr, 
        const uint8_t* in_pData)
    {
        (void)in_pArg;
        (void)in_pData;

        static uint32_t count = 0;
        fprintf(stdout, "Packet %u received, size %u\n", ++count, in_pPcapHdr->len);
    }

    void pcap_test_loop()
    {
        if (g_hPcapDev)
        {
            pcap_loop(g_hPcapDev, 0, pcap_test_handler, NULL);
        }
    }

**Comment by alainbrassardMeca** [comment] 2020-05-29 12:57
Another update:
Sometimes, there are just no packets received (instead of infinite loop of packets with length 0).
When that occurs, calling pcap_breakloop from another thread does not cause pcap_loop to exit as expected.

**Comment by alainbrassardMeca** [comment] 2020-05-29 13:03
Sometimes returns "corrupted" packet size too:

Opened pcap device 10.0.17.0 (\Device\NPF_{980B641D-4307-45B7-871D-45D1C8092FBC})
Packet 1 received, size 0
Packet 2 received, size 2275280104

**Comment by MaartenBent** [comment] 2020-05-29 13:29
I encounter the same problem (`header->len == 0`) in the callback and when using `pcap_next_ex` (same as #176 ?). But it does not seem related to the update to Windows 10 build 2004.
For me, [Npcap 0.9990](https://nmap.org/npcap/dist/npcap-0.9990.exe) works fine.

**Comment by alainbrassardMeca** [comment] 2020-05-29 13:53
You're right, I downgraded to npcap-0.9986 (which I happened to still have the installer), and the problem is gone, it works fine with that older version.

Looks like something was broken in 0.9991

**Comment by gvanem** [comment] 2020-05-29 13:57
> // Open the devices that matches the ip or subnet provided

What is this all about? And on Windows, you should call `pcap_lookupnet()`.

**Comment by alainbrassardMeca** [comment] 2020-05-29 14:02
You're right, I did not know about pcap_lookupnet, would be simpler than my iteration.
That's out of scope of this issue, but thanks for pointing out!

**Comment by MaartenBent** [comment] 2020-05-29 14:21
Some additional info. This also happens in the `basic_dump` example from the npcap sdk, capturing normal internet traffic on an ethernet port.

(The example also has access violations, fixed by adding `#include <time.h>`).

**Comment by guyharris** [comment] 2020-05-30 02:54
Just our of curiosity, what is the value of `in_pPcapHdr->caplen`?

**Comment by guyharris** [comment] 2020-05-30 03:51
The [Npcap Changelog](https://github.com/nmap/npcap/blob/master/CHANGELOG.md) says, [for 0.9991](https://github.com/nmap/npcap/blob/master/CHANGELOG.md#npcap-09991-2020-05-04):

> - Major changes to management of Npcap driver's circular packet buffer, switching from per-CPU unshared segments to a single worker thread managing a queue of work items. This improves buffer utilization, reduces the amount of time spent processing in the network stack, and should reduce packet loss. See [#1967](https://issues.nmap.org/1967).

That might have something to do with this.

**Comment by alainbrassardMeca** [comment] 2020-06-01 10:30
> Just our of curiosity, what is the value of `in_pPcapHdr->caplen`?

0. Everything is 0.

**Comment by dmiller-nmap** [comment] 2020-06-04 05:05
Duplicate of #168, fixed in Npcap 0.9992. Thanks for reporting!

**Closed by dmiller-nmap** 2020-06-04 05:05 UTC
