### ISSUE TITLE
Fatal exception: Failed to install NMAP - winpcap-nmap-latest.exe failed to install with code 2

### ISSUE THREAD

**Issue by bfrmm777** [nmap/npcap#635] opened 2022-09-22 11:25 UTC
**Describe the bug**
As part of Kaseya VSA Discovery it runs an installer called winpcap-nmap-latest.exe which opens up "Npcap OEM 1.00 setup". It gets as far as Installing NDIS filter and then errors with "Failed to create the npcap service for Win7, Win8 and Win10: 0x0004a020".

I can resolve this by running it in Win7 compatibility mode, however this then doesn't appear to register as already installed.

It's also working without any special conditions on a 2016 Server Standard x64 Edition Build 14393.

More info from the Kaseya's TaskRunner log:
[I 2022-09-22T08:18:16.666822Z +01:00 59760  954] [Script] Installing winpcap-nmap-latest.exe from path: C:\ProgramData\Kaseya\Data\task\xxx-xxx-xxx-xxx-xxx\nmap\winpcap-nmap-latest.exe
[I 2022-09-22T08:18:16.707827Z +01:00 59760 dbd8] [Process 45308] Created
[I 2022-09-22T08:18:16.707827Z +01:00 59760  dfc] [IOThread] Started
[I 2022-09-22T08:18:28.723357Z +01:00 59760 dbd8] [Process 45308] Exited(2)
[I 2022-09-22T08:18:28.723357Z +01:00 59760  dfc] [IOThread] Stopped
[E 2022-09-22T08:18:28.728358Z +01:00 59760  954] [Script] Failed to open existing key SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst with error "The system cannot find the file specified.

**Diagnostic information**
* Windows version from `winver`: Windows Server 2012 R2 v6.3 (Build 9600)
* If installation failed, include [SetupApi.dev.log](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/setupapi-device-installation-log-entries): Attached
[SetupApi.dev-npcap.log](https://github.com/nmap/npcap/files/9625104/SetupApi.dev-npcap.log)

**Additional context**
I have already raised this with Kaseya support and am getting nowhere, I'm not sure they fully understand the npcap install process.

**Comment by dmiller-nmap** [comment] 2022-10-03 19:02
This is a duplicate of #224, which was resolved in Npcap 1.55 and later by handling this error as meaning "succeeded, needs reboot." For earlier versions, we recommend first finishing any other installations, patches, or upgrades, then rebooting before attempting to install Npcap again. Depending on how the Kaseya installer handles existing Npcap installations, you may have better success with installing the latest Npcap (1.71) and then installing the Kaseya software. Be sure that "WinPcap API-compatible mode" is selected (currently default for new installations), since some software requires that.

**Closed by dmiller-nmap** 2022-10-03 19:02 UTC
