### ISSUE TITLE
Not able to block traffic using Npcap

### ISSUE THREAD

**Issue by sbrown89** [nmap/npcap#311] opened 2021-05-05 00:58 UTC
Windows 10:
![image](https://user-images.githubusercontent.com/7885241/117086725-611dd780-ad1b-11eb-9596-d2fa911a1080.png)

Npcap version 1.31
Added the needed registry keys:
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap\Parameters
  BlockRxAdapters \Device\\{6834AB76-46AB-49C2-9CFF-D391B6FF924D}
  SendToRxAdapters \Device\\{6834AB76-46AB-49C2-9CFF-D391B6FF924D}

![registry](https://user-images.githubusercontent.com/7885241/117086531-befdef80-ad1a-11eb-9c0c-6a899c32af8b.PNG)

Yes the GUID is the correct one for the adapter:
![image](https://user-images.githubusercontent.com/7885241/117086565-de951800-ad1a-11eb-800d-e946905a451c.png)

The service was restarted, box was restarted and verified the service is running:
![image](https://user-images.githubusercontent.com/7885241/117086605-0b492f80-ad1b-11eb-9be9-7d7451495367.png)

Packets always make it out of the adapter like normal. Any ideas?
Thanks for looking into this.

**Comment by guyharris** [comment] 2021-05-05 01:24
> Not able to block traffic using Npcap

That's not what Npcap is designed to do - it's designed to *passively capture* network traffic and let traffic be *passively injected*.  Have you written a program, using Npcap, that you expected to be able to block traffic?

**Comment by sbrown89** [comment] 2021-05-05 01:27
> > Not able to block traffic using Npcap
> 
> That's not what Npcap is designed to do - it's designed to _passively capture_ network traffic and let traffic be _passively injected_. Have you written a program, using Npcap, that you expected to be able to block traffic?

But it is. The driver has full support and config options to do just this. There is also older examples that describe creating a firewall for just this purpose. [user bridge + fw setup ](https://github.com/hsluoyz/UserBridge)

**Comment by dmiller-nmap** [comment] 2021-05-05 22:20
@sbrown89 Thanks for reporting this. We made what ought to have been a minor change in the code to read adapter names from the registry in Npcap 1.31, but this ought to still be supported. Does any previous version such as 1.30 work like you expect?

**Comment by sbrown89** [comment] 2021-05-06 00:53
@dmiller-nmap Yes, version 1.30 works as expected. Only the packets I allow and send back to npcap driver get through all others are blocked.

**Comment by guyharris** [comment] 2021-05-06 07:07
If this is to be a supported feature, it should be documented (somewhere other than an ancient release's release notes), and should perhaps be supported by packet.dll APIs.

**Comment by dmiller-nmap** [comment] 2021-05-06 17:04
@sbrown89 Thanks for checking that. I'll review the code change and see what can be done to resolve this issue.

@guyharris I agree that this feature is not well documented. I'm not sure whether it fits with Packet.dll, though, since it's not really about capture or injection. If a user needs this feature for their system, it has to be present from the time Npcap is inserted in the network stack at boot, which makes Registry the appropriate place. On the other hand, that makes it seem like Npcap ought to be a mandatory filter instead of optional as it currently is, which is a whole set of testing and support that we haven't looked at.

**Comment by fyodor** [comment] 2021-05-06 22:54
Thanks for the report.  We are hoping to fix this regression in the next Npcap release. I have also opened Issue #497 for evaluating this undocumented functionality as a whole.

**Comment by dmiller-nmap** [comment] 2021-06-22 23:35
This issue should be addressed in Npcap 1.50. We also made an improvement in this data path that you may notice as improved performance, though we did not measure that specifically. Let us know if you run into further problems.

**Closed by dmiller-nmap** 2021-06-22 23:35 UTC
