### ISSUE TITLE
Network adapter "Local Area Connection 9" is no longer attached; the capture has stopped

### ISSUE THREAD

**Issue by robpburns** [nmap/npcap#538] opened 2021-09-08 21:13 UTC
I had a USB/Ethernet adapter attached and was monitoring traffic using wireshark.  Error message is "The interface disappeared (error code ERROR_DEVICE_REMOVED/STATUS_DEVICE_REMOVED)"

The full version of Windows on which this occurreed ("64-bit Windows 7 Service Pack 1, build 7601");

The version of Npcap with which this occurred ("with Npcap version 1.31, based on libpcap version 1.10.1-PRE-GIT");

PC did not show any other malfunctions.  Ethernet cable was still plugged into USB/Ethernet adapter and USB/Ethernet adapter was still plugged into PC.

No other interfaces were added to or were removed from the machine when the capture was taking place.

**Comment by dmiller-nmap** [comment] 2021-09-09 15:54
Thanks for reporting this. This is a known issue (#250) for which we are considering the feasibility of a fix (#506). I am closing this issue as a duplicate of those.

**Closed by dmiller-nmap** 2021-09-09 15:54 UTC
