### ISSUE TITLE
BSOD in npcap.sys 1.80

### ISSUE THREAD

**Issue by inxxn** [nmap/npcap#755] opened 2024-10-20 12:00 UTC
When I create a PPPoE connection in Windows 10 LTSC 2021, as soon as I fill in the information provided by my ISP and click 'Connect', a BSOD occurs. I have captured the core memory dump and obtained the following content:
```
BUGCODE_NDIS_DRIVER (7c)
The operating system detected an error in a networking driver.
The BUGCODE_NDIS_DRIVER BugCheck identifies problems in network drivers.
Often, the defect is caused by a NDIS miniport driver. You can get a complete
list of NDIS miniport drivers using !ndiskd.netadapter.  You can get a
big-picture overview of the network stack with !ndiskd.netreport.
Arguments:
Arg1: 0000000000000021, NDIS_BUGCHECK_INVALID_OBJECT_HEADER
	A driver created an invalid NDIS_OBJECT_HEADER.
Arg2: ffff87836ce32850, The driver that indicated the illegal status
	indication. Use !ndiskd.miniport or
	!ndiskd.filter on this handle.
Arg3: ffff8783750969b8, The object with the malformed header. Its
	interpretation depends on the API being
	called. For example, if the driver called
	NdisAllocateCloneOidRequest, then cast
	the object to ndis!NDIS_OID_REQUEST.
Arg4: 0000000000000000, Zero.

Debugging Details:
------------------

Unable to load image \SystemRoot\system32\DRIVERS\npcap.sys, Win32 error 0n2

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 3249

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 16904

    Key  : Analysis.Init.CPU.mSec
    Value: 4577

    Key  : Analysis.Init.Elapsed.mSec
    Value: 77798

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 99

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1


FILE_IN_CAB:  MEMORY.DMP

BUGCHECK_CODE:  7c

BUGCHECK_P1: 21

BUGCHECK_P2: ffff87836ce32850

BUGCHECK_P3: ffff8783750969b8

BUGCHECK_P4: 0

BLACKBOXBSD: 1 (!blackboxbsd)


BLACKBOXNTFS: 1 (!blackboxntfs)


BLACKBOXPNP: 1 (!blackboxpnp)


BLACKBOXWINLOGON: 1

PROCESS_NAME:  System

STACK_TEXT:  
fffff289`d76d04e8 fffff804`77920377     : 00000000`0000007c 00000000`00000021 ffff8783`6ce32850 ffff8783`750969b8 : nt!KeBugCheckEx
fffff289`d76d04f0 fffff804`78d23dae     : ffff8783`750969b8 fffff289`d76d0649 00000000`00000000 00000000`00000000 : ndis!NdisAllocateCloneOidRequest+0x42057
fffff289`d76d0570 fffff804`778dc17d     : 00000000`00000000 00000000`00000000 fffff289`d76d0649 fffff289`d76d0649 : npcap+0x3dae
fffff289`d76d05a0 fffff804`724914a8     : 00000000`00000000 ffff8783`6feb1200 00000000`00000000 ffff8783`61a6d080 : ndis!ndisFDoOidRequestInternal+0x31d
fffff289`d76d06b0 fffff804`7249141d     : fffff804`778dbe60 ffff8783`6ce32850 00000000`00000000 ffff8783`750969b8 : nt!KeExpandKernelStackAndCalloutInternal+0x78
fffff289`d76d0720 fffff804`778ec15d     : ffff8783`6feb11a0 ffff8783`6ce32800 00000000`00000000 ffff8783`793590f8 : nt!KeExpandKernelStackAndCalloutEx+0x1d
fffff289`d76d0760 fffff804`778ec2a4     : 00000000`00000000 ffff8783`6feb11a0 ffff8783`750969b8 ffff8783`750969b8 : ndis!ndisQueueOidRequest+0x229
fffff289`d76d07d0 fffff804`778e81bb     : ffff8783`750969b8 fffff804`779b4048 ffff8783`750969b8 00000000`0000000a : ndis!ndisMOidRequest+0xa4
fffff289`d76d08b0 fffff804`c7c4e3a3     : ffff8783`75096ad0 ffff8783`750969b8 00000000`000000ff fffff804`00000000 : ndis!NdisOidRequest+0x5b
fffff289`d76d0900 fffff804`c7c550b4     : ffff8783`75096980 ffff8783`74644e01 00000000`00000008 00000000`00000000 : raspppoe!PrSetPacketFilterForAdapter+0xbf
fffff289`d76d0930 fffff804`c7c4e689     : ffff8783`79949ea0 ffff8783`7a7cb1c0 ffff8783`74644e50 ffff8783`7525d001 : raspppoe!ChangePacketFiltersForAdapters+0x1d8
fffff289`d76d0970 fffff804`c7c4e769     : ffff8783`79949f60 ffff8783`7525d080 fffff804`77909dd0 00000000`00000018 : raspppoe!ExecBindingWorkItem+0x109
fffff289`d76d09a0 fffff804`77909de2     : ffff8783`789f9b10 00000000`00000100 fffff804`77909dd0 ffff8783`5f872ce0 : raspppoe!WorkItemExec+0x29
fffff289`d76d09d0 fffff804`72543ea5     : 00000000`00000000 ffff8783`789f9b10 ffff8783`74644e50 fffff804`761ac660 : ndis!ndisDispatchIoWorkItem+0x12
fffff289`d76d0a00 fffff804`72422525     : ffff8783`61a6d080 ffff8783`61a6d080 fffff804`72543d70 00000000`00000000 : nt!IopProcessWorkItem+0x135
fffff289`d76d0a70 fffff804`72529905     : ffff8783`61a6d080 00000000`00000080 ffff8783`5f869040 000fa4ef`bd9bbfff : nt!ExpWorkerThread+0x105
fffff289`d76d0b10 fffff804`72607318     : ffffda80`ffbe0180 ffff8783`61a6d080 fffff804`725298b0 00000000`00000000 : nt!PspSystemThreadStartup+0x55
fffff289`d76d0b60 00000000`00000000     : fffff289`d76d1000 fffff289`d76ca000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x28


SYMBOL_NAME:  npcap+3dae

MODULE_NAME: npcap

IMAGE_NAME:  npcap.sys

STACK_COMMAND:  .cxr; .ecxr ; kb

BUCKET_ID_FUNC_OFFSET:  3dae

FAILURE_BUCKET_ID:  0x7C_21_npcap!unknown_function

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {dafc2f11-d8e6-0679-a10f-ef562a43f093}

Followup:     MachineOwner
---------

3: kd> lmvm npcap
Browse full module list
start             end                 module name
fffff804`78d20000 fffff804`78d33000   npcap      (no symbols)           
    Loaded symbol image file: npcap.sys
    Image path: \SystemRoot\system32\DRIVERS\npcap.sys
    Image name: npcap.sys
    Browse all global symbols  functions  data
    Timestamp:        Thu Aug 22 05:18:42 2024 (66C659B2)
    CheckSum:         00017E78
    ImageSize:        00013000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4
    Information from resource tables:

```

**Comment by dmiller-nmap** [comment] 2024-10-21 18:05
Duplicate of #296

**Closed by dmiller-nmap** 2024-10-21 18:05 UTC

**Comment by r4v3n6** [comment] 2024-10-22 13:32
This is not old duplicate from 2021 bug. The issue didn't happen in 1.78, but happens directly when upgrading to 1.79. So it is a new regression issue introduced in 1.79.
