### ISSUE TITLE
The promiscuous mode bug is also not resolved in npcap 1.73 version

### ISSUE THREAD

**Issue by youngbeggar** [nmap/npcap#665] opened 2023-04-01 04:28 UTC
My computer spec is Windows 11, Realtek LAN card, and I installed Npcap version 1.73

But the promiscuous mode bug is also not resolved to my computer.

How do I fix promiscuous mode bug?

![bug](https://user-images.githubusercontent.com/129573608/229265580-e5d07d69-6633-452d-8573-612459c38821.png)

**Comment by guyharris** [comment] 2023-04-01 06:25
> How do I fix promiscuous mode bug?

By figuring out why the NDIS stack or the driver for the network adapter is failing to allow the packet filter to be set, and either

1. if it's a driver bug, getting the driver fixed;
2. if it's an NDIS stack bug, getting Microsoft to fix the NDIS stack;
3. if it's an Npcap driver bug, indicating what needs to be fixed in the Npcap driver.

In any case, this is a duplicate of issue #628 - which is still open - and should be closed as such.

**Comment by alglove** [comment] 2023-04-01 18:16
youngbeggar, you can try downgrading to version 1.60 until this issue gets resolved. But as guyharris says, this is a duplicate of #628 , so you can follow that thread for further updates.

**Comment by fyodor** [comment] 2023-04-01 18:45
Thanks for the report.  We're working to figure out the cause. I'm closing this as a duplicate of #628 to consolidate the discussion there.

**Closed by fyodor** 2023-04-01 18:45 UTC
