### ISSUE TITLE
npcap does not work on windows 11 virtual machine in mac

### ISSUE THREAD

**Issue by weixin-you** [nmap/npcap#602] opened 2022-06-01 03:25 UTC
<img width="647" alt="image" src="https://user-images.githubusercontent.com/105306425/171321642-d50aeccf-2d46-4835-b4d8-885d9028dfd2.png">
as shown above. Even I installed npcap, the issue existed.

**Comment by weixin-you** [comment] 2022-06-01 16:09
I need to add some information: I am using a MacBook m1 and using parallel. so the windows system is installed on parallel.

**Comment by guyharris** [comment] 2022-06-01 19:29
> I am using a MacBook m1

So is this an x86-64 version of Windows or an ARM64 version of Windows that's running in Parallels?

**Comment by guyharris** [comment] 2022-06-01 20:34
And this is an x86-64 version of Wireshark for Windows, as Wireshark isn't yet built for ARM64 on Windows.

I.e., this is probably a dup of #585.

**Comment by fyodor** [comment] 2022-06-20 18:37
Thanks folks.  I'm closing this as a duplicate of #585 as described.

**Comment by fyodor** [comment] 2022-06-20 18:37
Duplicate of #585

**Closed by fyodor** 2022-06-20 18:37 UTC
