### ISSUE TITLE
Npcap Bug Report - install failure on Windows Server 2008r2 (0.9994 and 0.9995)

### ISSUE THREAD

**Issue by timg11** [nmap/npcap#222] opened 2020-08-08 16:33 UTC
When I upgraded Wireshark to 3.2.5 on Windows Server 2008r2, the installation failed. The npcap installer hung indefinitely with no cancel buttons. I restarted the server, uninstalled Wireshark, and tried again. 
It continues to fail. I have also verified that npcap is uninstalled, and the c:\program files\npcap directory is empty except the installer logs. 

I tried installing npcap 0.9995 from the installer npcap-0.9995.exe. It also fails.  Install logs are attached. 

[NPFInstall-2020-08-08.log](https://github.com/nmap/npcap/files/5045621/NPFInstall-2020-08-08.log)
[instal-2020-08-08l.log](https://github.com/nmap/npcap/files/5045622/instal-2020-08-08l.log)

After rebooting again and ensuring all npcap files except the logs were gone, I tried installing Wireshark 3.2.5 again with the embedded npcap 0.9994.  I used these options for npcap:

![wireshark 994 2020-08-08_111842](https://user-images.githubusercontent.com/12547510/89715337-a9fe5680-d96a-11ea-952d-603e3e45fa2c.png)

The installer pauses for a long time here:
![long delay here 2020-08-08_111922](https://user-images.githubusercontent.com/12547510/89715343-b4205500-d96a-11ea-9ea2-7fd3f7a9377e.png)

Then fails like this:
![Fail 994 with wireshark 2020-08-08_111946](https://user-images.githubusercontent.com/12547510/89715348-be425380-d96a-11ea-944d-0caf8d1035a5.png)

With Details:
![with details 2020-08-08_113917](https://user-images.githubusercontent.com/12547510/89715574-129a0300-d96c-11ea-96d8-8bb63926c03d.png)

![aborted 994 2020-08-08_112008](https://user-images.githubusercontent.com/12547510/89715351-c601f800-d96a-11ea-9d14-88c876784893.png)

**Comment by dmiller-nmap** [comment] 2020-08-26 21:37
Thanks for this report. Error 4a020 means this is a duplicate of #224. Please try this procedure and comment on #224 if you still have problems:

1. Uninstall any remaining Npcap installation.
2. Reboot.
3. Install Npcap 0.9997

**Closed by dmiller-nmap** 2020-08-26 21:37 UTC
