### ISSUE TITLE
After installing NPcap 1.79, a blue screen crash occurred when attempting to connect to the Internet through dial-up.

### ISSUE THREAD

**Issue by kumu7y** [nmap/npcap#726] opened 2024-04-25 10:28 UTC
**Describe the bug**
After installing npcap1.79, a blue screen crash occurred while attempting to connect to the Internet via dial-up.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Diagnostic information**
Version Windows 11 Home Edition
Version 23H2
Installation date ‎2024/‎4/‎24
Operating system version 22631.3527
Experience Windows Feature Experience Pack 1000.22700.1003.0

**Additional context**
[
[042524-16734-01.dmp](https://github.com/nmap/npcap/files/15108236/042524-16734-01.dmp)
](url)

**Comment by dmiller-nmap** [comment] 2024-09-16 22:47
Duplicate of #296

**Closed by dmiller-nmap** 2024-09-16 22:47 UTC

**Comment by r4v3n6** [comment] 2024-10-22 13:34
This is not old duplicate from 2021 bug. The issue didn't happen in 1.78, but happens directly when upgrading to 1.79. So it is a new regression issue introduced in 1.79. It happened on 2 separate Windows 11 devices for me when upgrading to latest Wireshark which upgraded NPCap from 1.78 to 1.79.
