### ISSUE TITLE
Npcap failed to create the npcap service: 0x8007007e

### ISSUE THREAD

**Issue by BenedictoBoseke** [nmap/npcap#593] opened 2022-04-11 07:12 UTC
![image](https://user-images.githubusercontent.com/78397483/162683273-1d7898f3-f7fb-461a-8a1c-fdcdc2f2b287.png)
This happened when I'm installing Npcap version 1.6 on windows 10 21H2

Output folder: C:\Users\USER\AppData\Local\Temp\nsoE348.tmp
Extract: NPFInstall.exe
Output folder: C:\Program Files\Npcap
Extract: LICENSE
Extract: DiagReport.bat
Extract: DiagReport.ps1
Extract: FixInstall.bat
Extract: Uninstall.exe
Output folder: C:\Windows\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Windows\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Program Files\Npcap
Extract: NPFInstall.exe
Installing NDIS6 x64 driver for Win10
Output folder: C:\Program Files\Npcap
Extract: npcap.sys
Extract: npcap.cat
Extract: npcap.inf
Extract: npcap_wfp.inf
Output folder: C:\Windows\system32
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Windows\system32\Npcap
Extract: wpcap.dll
Extract: Packet.dll
Extract: NpcapHelper.exe
Extract: WlanHelper.exe
Output folder: C:\Users\USER\AppData\Local\Temp\nsoE348.tmp
Extract: roots.p7b
Adding roots.p7b to store "Root"
Delete file: C:\Users\USER\AppData\Local\Temp\nsoE348.tmp\roots.p7b
Output folder: C:\Users\USER\AppData\Local\Temp\nsoE348.tmp
Extract: signing.p7b
Adding signing.p7b to store "TrustedPublisher"
Delete file: C:\Users\USER\AppData\Local\Temp\nsoE348.tmp\signing.p7b
Clearing Npcap entries from driver store
Npcap driver cache in Driver Store has been successfully cleaned up!
Installing WFP callout driver
Npcap WFP callout driver has been successfully installed!
Installing NDIS filter driver
Unknown error! 8007007e
Npcap LWF driver has failed to be installed.
Failed to create the npcap service for Win7, Win8 and Win10: 0x8007007e
Writing service options to registry
RunUninstaller: "C:\Program Files\Npcap\Uninstall.exe" /Q /keep_logs=yes /force=yes _?=C:\Program Files\Npcap
Delete file: C:\Program Files\Npcap\Uninstall.exe

**Comment by Kanglatae** [comment] 2022-07-16 06:29
I have this same issue. I notice the error comes when **Installing NDIS filter driver**.
Did you figure it out?

**Comment by Startrek2020** [comment] 2022-10-02 10:31
Same issue here - 
DetailPrint: Failed to create the npcap service for Win7, Win8 and Win10: 0x80070005
MessageBox: 2097152,"Failed to create the npcap service: 0x80070005. Please try installing Npcap again, or use the latest official Npcap installer from https://npcap.org/"

**Comment by H3nryM** [comment] 2022-11-07 03:29
Same issue here. Has anyone fixed this?

**Comment by aliencaocao** [comment] 2022-11-24 11:14
same issue

**Comment by guyharris** [comment] 2023-08-14 06:33
Same issue as #135?

**Comment by 3shadow7** [comment] 2023-10-04 02:38
i have the same , i download 1.73v and 1.77v the last version , and give me the same issue , Has anyone fixed this?

**Comment by fyodor** [comment] 2023-11-27 18:58
Duplicate of #135

**Closed by fyodor** 2023-11-27 18:58 UTC

**Comment by atharimran728** [comment] 2025-08-03 09:41
https://www.youtube.com/watch?v=cDXDY67u6nE

This video provides several solutions that work for me.
