### ISSUE TITLE
Winpcap + npcap: some packets not received

### ISSUE THREAD

**Issue by christophe-calmejane** [nmap/npcap#655] opened 2023-01-09 09:58 UTC
Hi,
I'm facing a very weird issue when both winpcap and npcap are installed.
After an application using winpcap is closed (closing its pcap instance), another application using npcap will not receive some packets anymore.
I'm not sure what's the exact interaction, if the pcap filter has anything to do with it, the type of packets... but I can reproduce 100% of the time with the following steps.

**To Reproduce**
1. Start an application that will try to load winpcap, and set up a single filter: `"ether proto 0x22f0"`
2. Start Wireshark (a version using npcap natively if present, not winpcap)
3. Setup a filter to display AVDECC messages `"ieee17221"`
4. Have a device sending AVDECC messages, like a Mac computer (need to setup correctly the interface by enabling AVB through `avbutil`)
5. Observe in wireshark `AVDECC Discovery` messages (ieee1722.subtype==0xfa)
6. Stop the application using winpcap
7. Observe in wireshark that no `AVDECC Discovery` messages are received anymore, but other AVDECC messages are correctly received.
8. Restarting the application using winpcap causes messages to be received once again

**Expected behavior**
Continue to receive all messages when using winpcap and npcap altogether.

**Additional context**
* What I noticed is that only `MULTICAST` messages are no longer received, all other messages (including other AVDECC unicast messages) are properly received by applications using npcap
* An example of an application using winpcap and setting up a ether proto filter can be found here: https://github.com/christophe-calmejane/Hive/releases/tag/v1.2.8 (do not use more recent version than this one, as newer version support npcap natively)

**Comment by dmiller-nmap** [comment] 2023-01-24 20:59
Thanks for this report. Does the issue happen with Npcap before version 1.70? I believe this may be caused by the bug in issue #647. If Npcap 1.60 does not exhibit the same behavior, then we will mark this as a duplicate of that issue, expecting it to be resolved in the next release.

**Comment by christophe-calmejane** [comment] 2023-01-25 11:29
Hi, thanks for the response.
Interestingly, I'm pretty sure I tested with the latest npcap version available at the time of my findings (Jan, 6th), but it looks like npcap 1.72 was already released, so maybe I messed up.

Nevertheless, npcap 1.60 doesn't exhibit the bug nor does npcap 1.72, so I guess it's the same issue which is now fixed.
You may close this then, I'll monitor this issue on my side and ask for reopen in case it's actually something different. Thanks

**Comment by dmiller-nmap** [comment] 2023-01-30 19:31
Duplicate of #647

**Closed by dmiller-nmap** 2023-01-30 19:31 UTC
