### ISSUE TITLE
npcap installation issue

### ISSUE THREAD

**Issue by sourav-sharma035** [nmap/npcap#524] opened 2021-07-21 21:03 UTC
Hello Concern,
I need your help for re-installing npcap. When I trying to install npcap in my windows server 2012 R2, it shows the error "failed to create a npcap service". I was trying some solutions by googling, but I'm unable to find out the solution regarding this issue. It's really helpful for me if you give the solution regarding this issue. I attached the install log file and some screenshots for your understanding.

[attachment](https://drive.google.com/drive/folders/13ilyP1Q68W1eQ2xsx-oKIVwfpgfEZmsC?usp=sharing)

**Comment by fyodor** [comment] 2021-08-15 18:03
Hi.  I cannot read your attachment (Google drive says I have no access) but I think is probably a duplicate of #233 which we hope to fully resolve in the next release.

**Comment by fyodor** [comment] 2021-08-15 18:04
Duplicate of #233

**Closed by fyodor** 2021-08-15 18:04 UTC
