### ISSUE TITLE
wireshark Can't get list of interfaces: PacketGetAdapterNames: The system cannot find the path specified. (3)

### ISSUE THREAD

**Issue by dribniff** [nmap/npcap#575] opened 2022-01-06 02:51 UTC
Just updated to Wireshark 3.6.1 and the attached latest npcap and got this at Wireshark start up

wireshark Can't get list of interfaces: PacketGetAdapterNames: The system cannot find the path specified. (3)

What just happened?

DiagReport attached 
[DiagReport-20220105-202932.txt](https://github.com/nmap/npcap/files/7819143/DiagReport-20220105-202932.txt)

**Comment by kpatil001** [comment] 2022-01-06 11:53
I am facing same problem

**Comment by ruycesar** [comment] 2022-01-07 06:10
same here
[DiagReport-20220106-234602.txt](https://github.com/nmap/npcap/files/7826818/DiagReport-20220106-234602.txt)

**Comment by dribniff** [comment] 2022-01-14 15:53
Wireshark docs point at this being an NPCAP deal.

**Comment by MackTuesday** [comment] 2022-01-16 01:34
Same problem
[DiagReport-20220115-190658.txt](https://github.com/nmap/npcap/files/7876213/DiagReport-20220115-190658.txt)

**Comment by dmiller-nmap** [comment] 2022-01-19 18:45
This is a known issue with Npcap 1.50 and 1.55 on Windows 7 that is fixed in Npcap 1.60. The issue is #536 .

**Closed by dmiller-nmap** 2022-01-19 18:45 UTC

**Comment by dribniff** [comment] 2022-01-20 02:19
Overlayed v1.6 and rebooted.  Just like that, I have interfaces again.  Thank you for the reply.

**Comment by egocarib** [comment] 2022-05-07 14:53
I also am encountering this issue. Just did a fresh install of Wireshark on Windows 10. Encountered this issue (Wireshark came with npcap 1.55). I saw suggestions to upgrade to npcap 1.60, so I did that and rebooted, but the `Can't get list of interfaces: PacketGetAdapterNames: The system cannot find the path specified. (3)` message persists.

```
Running on 64-bit Windows 10 (21H2), build 19044, with 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (with SSE4.2),
with 32469 MB of physical memory, with GLib 2.66.4, with Qt 5.15.2, with Npcap version 1.60, based on libpcap version
1.10.2-PRE-GIT, with c-ares 1.17.0, with GnuTLS 3.6.3, with Gcrypt 1.8.3, with nghttp2 1.44.0, with brotli 1.0.9,
with LZ4 1.9.3, with Zstandard 1.4.0, without AirPcap, with light display mode, with HiDPI,
with LC_TYPE=English_United States.utf8, binary plugins supported (21 loaded). 
```

**Comment by ProfessorSteveH** [comment] 2022-05-13 19:27
Same here - Wireshark 3.6.5 with npcap 1.60 on Win 7 x64 sp1.

**Comment by KyroOW** [comment] 2022-06-19 18:39
Getting it as well, Wireshark 3.6.6 npcap 1.60 on Windows 10 x64.
