### ISSUE TITLE
whireshark network adapter no longer attached

### ISSUE THREAD

**Issue by makiwaki** [nmap/npcap#504] opened 2021-06-05 05:36 UTC
Hi Team,
during tracing network traffic over night with wireshark i found at  the next morning an error popup which asked to report an issue to you. 
Details:
Network adapter Ethernet 2 not longer attached
Error Message "The interface disappeared", Error code "ERROR_DEVICE_REMOVED/STATUS_DEVICE_REMOVED"
Windows 64-bit, Windows 10 (2009), build 19042
Npcap version 1.31, based on libpcap version 1.10.1-PRE-GIT

PC was in standby in the morning. Windows events showed 
errorCode 0x80240017 
  updateTitle Security Intelligence-Update für Microsoft Defender Antivirus - KB2267602 (Version 1.341.8.0)
and Event 37, Kernel processor Power, pace of processor is reduced due to system firmware.

Bes Regards
Markus

**Comment by guyharris** [comment] 2021-06-06 23:02
The full instructions in Wireshark also include, in the "Give all details, such as" section:

> Any indication of whether the machine went to sleep during the capture;       
> Any indication of whether any other interfaces were added to or removed from the machine while the capture was taking place.

It sounds as if you weren't watching the machine while it was capturing, in which case you don't know whether it went to sleep during the capture, and, unless somebody else added or removed an interface, no other interfaces were added to or removed from the machine while the capture was taking place.  Is that the case?

**Comment by makiwaki** [comment] 2021-06-07 05:37
Hi,
The laptop went asleep during capturing as I tried to find any device in my very small Network sending packages during the night. And yes, no other Interfaces were removed or added. I used a Docking station connected via USB to the laptop. In that Docking station is the Ethernet cable plugged.
Regards Markus

Am 7. Juni 2021 01:03:06 MESZ schrieb Guy Harris ***@***.***>:
>The full instructions in Wireshark also include, in the "Give all
>details, such as" section:
>
>> Any indication of whether the machine went to sleep during the
>capture;       
>> Any indication of whether any other interfaces were added to or
>removed from the machine while the capture was taking place.
>
>It sounds as if you weren't watching the machine while it was
>capturing, in which case you don't know whether it went to sleep during
>the capture, and, unless somebody else added or removed an interface,
>no other interfaces were added to or removed from the machine while the
>capture was taking place.  Is that the case?

**Comment by guyharris** [comment] 2021-06-07 06:04
See also #250.

**Comment by dmiller-nmap** [comment] 2021-06-07 21:23
This error happens when NDIS detaches Npcap's filter driver from the adapter, as discussed at #250. For long-running captures, we recommend minding the software and restarting the capture as soon as this error is seen. This can be done directly with dumpcap.exe, but I do not know whether Wireshark supports it directly. Usually a system sleep does not cause this problem, and I have tested a Wireshark capture with Npcap that resumed just fine after closing and opening the laptop lid. A hibernate might be different, but that doesn't sound like what happened here.

I am closing this as a duplicate of #250. I have opened #506 for discussion of a new feature to work around this behavior.

**Closed by dmiller-nmap** 2021-06-07 21:23 UTC
